### ISSUE TITLE
Major integrity error as ur secret is publicly available 

### ISSUE THREAD

**Issue by bugslayer01** [Fyxod/cryptic#4]
You are not even calling your env file  in your jwtfuncs.js so as per your code ur jwt secret is set to "notaverygoodsecret"

![image](https://github.com/user-attachments/assets/6e55fb96-03a2-4fb1-b50e-481cc59eb568)

**Comment by Fyxod** [comment]
Sorry sir, will fix it

**Comment by bugslayer01** [comment]
if u want i can do it for u  just buy me ice tea

**Comment by Fyxod** [comment]
Sure, make a pr

**Comment by Fyxod** [comment]
The mistake of this nincompoop has been fixed owing to you.
